### PR TITLE
Just Small contribution 👍 

### PR DESCRIPTION
**Pull request by geeks121**
1. added run.py to make it simple runing this bot
2. Make A copy BSCtokenSniper modified for Linux
3. Add screenshot
4. Update Readme.md

Why i created linux version?

Because current version not able to run in linux and give the error. It because ctype.windll.kernel32, after working to fix it and it work like charm in Ubuntu Linux.

web3 from nodejs not needed here. i don't know why. i'm not expert as you.

### CODE REVIEW

**Comment by geeks121** [comment]
websocket fixed the freezing

**Comment by littlewe1337** [comment]
[05:04:29.318] [Info] Web3 successfully connected
Traceback (most recent call last):
  File "C:\Users\Are U OHUELI TAM\Downloads\BSCTokenSniper-main\BSCTokenSniper-main\BSCTokenSniper_wss.py", line 78, in <module>
    obj = json.loads(data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 16 column 4 (char 611)


What's wrong? It's the first time this has happened. This is after the update 20 minutes ago

**Comment by geeks121** [comment]
can you run for linux_wss ?

**Comment by geeks121** [comment]
reconfigure your config.json see in my fork..

**Comment by littlewe1337** [comment]
> reconfigure your config.json see in my fork..

I updated config.json, the error occurs with the updated file and my data

**Comment by geeks121** [comment]
it strange i just add the mini audit 
did you add : 
checkPancakeV1Router = obj['checkPancakeV1Router'],
checksolidity4 = obj['checksolidity4']

already?

i forgot to add comas add end pancakeswap, sory ,, can you rerun it?

**Comment by littlewe1337** [comment]
> it strange i just add the mini audit
> did you add :
> checkPancakeV1Router = obj['checkPancakeV1Router'],
> checksolidity4 = obj['checksolidity4']
> 
> already?
> 
> i forgot to add comas add end pancakeswap, sory ,, can you rerun it?
> 
> how the code now? you can open issue in my fork. feel free

https://i.imgur.com/OUkWNpB.png

I tried to open it on your fork, but it redirects me to the original (

**Comment by geeks121** [comment]
can you show config.json pointed to :
   "checkHoneypot": "True",
   "checkPancakeV1Router": "True",
   "checksolidity4": "True"

it should be ended with comas : "checkPancakeV1Router": "True",

**Comment by littlewe1337** [comment]
> можете ли вы показать config.json, указывающий на:
> "checkHoneypot": "True",
> "checkPancakeV1Router": "True",
> "checkolidity4": "True"
> 
> он должен заканчиваться запятыми: "checkPancakeV1Router": "True",

Yes, there was a mistake, there was a comma missing. Thank you!

**Comment by littlewe1337** [comment]
Can you tell me when to expect autosale tokens? Or leave your contact so I can get in touch with you

**Comment by geeks121** [comment]
i still learning to python and web3 .. i want to add it too..
fauzinurhaqin.github.io

**Comment by littlewe1337** [comment]
> i still learning to python and web3 .. i want to add it too..
> fauzinurhaqin.github.io

its mail or telegram?

**Comment by geeks121** [comment]
telegram,, you can contact me in twitter... i prefer twitter btw

**Pull request closed without merging**
